---
- name: collect device facts and running configs
  hosts: all
  gather_facts: yes
  connection: network_cli

  roles:
    - role: network-facts

  tasks:
    - debug:
        msg: "Device {{ inventory_hostname }} is type {{ ansible_network_os }} running software version {{ version }}"
