- name: Get Cisco PSIRT API Token
  uri:
    url: https://cloudsso.cisco.com/as/token.oauth2
    method: POST
    body_format: form-urlencoded
    body: "client_id=r6fj4chscmx2t7sh43ay65mb&client_secret=9mKj7xSTGttNMjFq8pNz8Jhf&grant_type=client_credentials"
    headers:
      Accept: application/json
      Content-Type: application/x-www-form-urlencoded
    status_code: 200
  register: login_token
  run_once: true
  delegate_to: localhost

- name: Get Cisco PSIRT CVE List NXOS
  uri:
    url: "https://api.cisco.com/security/advisories/nxos?version={{ item.key }}&?pageIndex=1&pageSize=100"
    method: GET
    headers:
      Accept: application/json
      Authorization: "Bearer {{ login_token.json.access_token }}"
    status_code: 200
  register: nxos_cve_list
  run_once: true
  loop: "{{ device_data.nxos | default({}) | dict2items  }}"
  loop_control:
    label: "{{ item.key }}"
  when: device_data.nxos is defined

- name: Get Cisco PSIRT CVE List IOS
  uri:
    url: https://api.cisco.com/security/advisories/ios?version={{ item.key }}&?pageIndex=1&pageSize=1
    method: GET
    headers:
      Accept: application/json
      Authorization: "Bearer {{ login_token.json.access_token }}"
    status_code: 200
  register: ios_cve_list
  run_once: true
  loop: "{{ device_data.ios | default({}) | dict2items  }}"
  loop_control:
    label: "{{ item.key }}"
  when: device_data.ios is defined

- name: Get Cisco PSIRT CVE List IOS-XE
  uri:
    url: https://api.cisco.com/security/advisories/iosxe?version={{ item.key }}&?pageIndex=1&pageSize=1
    method: GET
    headers:
      Accept: application/json
      Authorization: "Bearer {{ login_token.json.access_token }}"
    status_code: 200
  register: iosxe_cve_list
  run_once: true
  loop: "{{ device_data.iosxe | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: device_data.iosxe is defined

#cve_mapping filter is found in filter_plugs>cve_mapping.py
- name: Set NXOS CVE mapping as fact
  set_fact:
    nxos_cves: "{{ nxos_cve_list | cve_mapping('nxos') }}"
  run_once: true
  when: device_data.nxos is defined

- name: Set IOS CVE mapping as fact
  set_fact:
    ios_cves: "{{ ios_cve_list | cve_mapping('ios') }}"
  run_once: true
  when: device_data.ios is defined

- name: Set IOS-XE CVE mapping as fact
  set_fact:
    iosxe_cves: "{{ iosxe_cve_list | cve_mapping('iosxe') }}"
  run_once: true
  when: device_data.iosxe is defined

- name: Merge IOS CVEs into main dictionary
  set_fact:
    cve_data: "{{ device_data|combine(ios_cves, recursive=true) }}"
  run_once: true
  when: ios_cves is defined

- name: Merge IOS-XE CVEs into main dictionary
  set_fact:
    cve_data: "{{ cve_data|combine(iosxe_cves) }}"
  run_once: true
  when: iosxe_cves is defined

- name: Merge NXOS CVEs into main dictionary
  set_fact:
    cve_data: "{{ cve_data|combine(nxos_cves,recursive=true) }}"
  run_once: true
  when: nxos_cves is defined
