- name: Get Cisco PSIRT API Token
  uri:
    url: https://cloudsso.cisco.com/as/token.oauth2
    method: POST
    body_format: form-urlencoded
    body: "client_id={{ cisco_psirt_clientid }}&client_secret={{ cisco_psirt_clientsecret }}&grant_type=client_credentials"
    headers:
      Accept: application/json
      Content-Type: application/x-www-form-urlencoded
    status_code: 200
  register: login_token
  run_once: true
  delegate_to: localhost

- name: Get Cisco PSIRT CVE List NXOS
  uri:
    url: "https://api.cisco.com/security/advisories/nxos?version={{ item.key }}&?pageIndex=1&pageSize=100"
    method: GET
    headers:
      Accept: application/json
      Authorization: "Bearer {{ login_token.json.access_token }}"
    status_code: 200
  register: nxos_cve_list
  run_once: true
  loop: "{{ device_data.nxos | default({}) | dict2items  }}"
  loop_control:
    label: "{{ item.key }}"
  when: device_data.nxos is defined
  delegate_to: localhost

- name: Get Cisco PSIRT CVE List IOS
  uri:
    url: https://api.cisco.com/security/advisories/ios?version={{ item.key }}&?pageIndex=1&pageSize=1
    method: GET
    headers:
      Accept: application/json
      Authorization: "Bearer {{ login_token.json.access_token }}"
    status_code: 200
  register: ios_cve_list
  run_once: true
  loop: "{{ device_data.ios | default({}) | dict2items  }}"
  loop_control:
    label: "{{ item.key }}"
  when: device_data.ios is defined
  delegate_to: localhost

- name: Get Cisco PSIRT CVE List IOS-XE
  uri:
    url: https://api.cisco.com/security/advisories/iosxe?version={{ item.key }}&?pageIndex=1&pageSize=1
    method: GET
    headers:
      Accept: application/json
      Authorization: "Bearer {{ login_token.json.access_token }}"
    status_code: 200
  register: iosxe_cve_list
  run_once: true
  loop: "{{ device_data.iosxe | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: device_data.iosxe is defined
  delegate_to: localhost
