- name: Set Current Date as Fact
  set_fact:
    current_date: "{{ now() }}"
  delegate_to: localhost
  run_once: true

- name: Set Confluence child page title with timestamp
  set_fact:
    confluence_child_title: "{{ confluence_parent_title }} - {{ current_date }}"
  delegate_to: localhost
  run_once: true

#Get existing pages to determine if we need to create or update it
- name: Get Confluence Pages
  uri:
    url: https://{{ confluence_url }}/wiki/rest/api/space/{{ confluence_space }}/content?expand=body.storage,version
    method: GET
    user: "{{ confluence_user }}"
    password: "{{ confluence_token }}"
    force_basic_auth: yes
    status_code: 201,200
    body_format: json
  register: confluence_pages
  run_once: true

- name: Set Confluence Data as Facts
  set_fact:
    confluence_page_titles: "{{ confluence_pages.json.page.results | map(attribute='title')|list }}" #Map all page titles to list for searching
    confluence_parent_page_id: "{{ confluence_pages | json_query(confluence_parent_query) }}" #Query is found in defaults/main.yml
  run_once: true

- name: Get Confluence Page Version
  uri:
    url: "https://{{ confluence_url }}/wiki/rest/api/content/{{ confluence_parent_page_id[0] }}"
    method: GET
    user: "{{ confluence_user }}"
    password: "{{ confluence_token }}"
    force_basic_auth: yes
    status_code: 201,200
    body_format: json
  register: confluence_version_json
  run_once: true
  when: confluence_parent_page_id | length

- name: Set Confluence Version as Fact
  set_fact:
    confluence_page_version: "{{ confluence_version_json.json.version.number | int + 1 }}" #API requires you to increment by 1 the version
  run_once: true
  when: confluence_parent_page_id | length

- name: Create Parent Page
  block:
    - debug:
        msg: "{{ lookup('template','templates/confluence_parent.j2') }}"

    - name: Create Network CVE Parent Page
      uri:
        url: https://{{ confluence_url }}/wiki/rest/api/content/
        method: POST
        user: "{{ confluence_user }}"
        password: "{{ confluence_token }}"
        force_basic_auth: yes
        status_code: 201,200
        body: "{{ lookup('template','templates/confluence_parent.j2') }}"
        body_format: json
      run_once: true
  when:
    - confluence_parent_title is defined
    - confluence_parent_title not in confluence_page_titles

- name: Create Network CVE Child Page
  uri:
    url: https://{{ confluence_url }}/wiki/rest/api/content/
    method: POST
    user: "{{ confluence_user }}"
    password: "{{ confluence_token }}"
    force_basic_auth: yes
    status_code: 201,200
    body: "{{ lookup('template','templates/confluence_child.j2') }}"
    body_format: json
  register: create_child_page
  run_once: true
  when:
    - confluence_parent_title is defined
