#cve_mapping filter is found in filter_plugs>cve_mapping.py
- name: Set NXOS CVE mapping as fact
  set_fact:
    nxos_cves: "{{ nxos_cve_list | cve_mapping('nxos') }}"
  run_once: true
  when: device_data.nxos is defined
  delegate_to: localhost

- name: Set IOS CVE mapping as fact
  set_fact:
    ios_cves: "{{ ios_cve_list | cve_mapping('ios') }}"
  run_once: true
  when: device_data.ios is defined
  delegate_to: localhost

- name: Set IOS-XE CVE mapping as fact
  set_fact:
    iosxe_cves: "{{ iosxe_cve_list | cve_mapping('iosxe') }}"
  run_once: true
  when: device_data.iosxe is defined
  delegate_to: localhost

- name: Create main CVE data dictionary
  set_fact:
    cve_data: {}
  run_once: true
  when: ios_cves is defined
  delegate_to: localhost

- name: Merge Network Device Data with main dictionary
  set_fact:
    cve_data: "{{ cve_data|combine(device_data, recursive=true) }}"
  run_once: true
  when: ios_cves is defined
  delegate_to: localhost

- name: Merge IOS CVEs into main dictionary
  set_fact:
    cve_data: "{{ cve_data|combine(ios_cves, recursive=true) }}"
  run_once: true
  when: ios_cves is defined
  delegate_to: localhost

- name: Merge IOS-XE CVEs into main dictionary
  set_fact:
    cve_data: "{{ cve_data|combine(iosxe_cves, recursive=true) }}"
  run_once: true
  when: iosxe_cves is defined
  delegate_to: localhost

- name: Merge NXOS CVEs into main dictionary
  set_fact:
    cve_data: "{{ cve_data|combine(nxos_cves, recursive=true) }}"
  run_once: true
  when: nxos_cves is defined
  delegate_to: localhost
