---
- name: Clone the backup repo
  git:
    repo: "{{ cve_data_repository }}"
    dest: "{{ cve_data_dir }}"
    accept_hostkey: yes
    force: yes
    key_file: "~/.ssh/id_rsa"
  register: clone_result
  delegate_to: localhost
  run_once: true
  when:
    - cve_data_repository is defined
    - cve_data_dir is defined

- name: Create CVE data file
  copy:
    dest: "{{ cve_data_file }}"
    content: "{{ cve_data | to_nice_json }}"
  delegate_to: localhost
  run_once: true
  when:
    - cve_data_file is defined

- name: Add CVE data to the repository
  block:
    - name: Add CVE data to repo
      command: "git add *.json"
      args:
        chdir: "{{ cve_data_dir }}"
      delegate_to: localhost
      changed_when: False
      run_once: true

    - name: Get the status of the repository
      command: "git status"
      args:
        chdir: "{{ cve_data_dir }}"
      register: status_results
      changed_when: False
      ignore_errors: yes
      delegate_to: localhost
      run_once: true

    - name: Get Current Date
      set_fact:
        current_date: "{{ lookup('pipe','date +%m-%d-%H-%M') }}"
      delegate_to: localhost
      run_once: true

    - name: Commit the changes
      command: "git commit -am 'CVE Data Backup - {{ current_date }}'"
      args:
        chdir: "{{ cve_data_dir }}"
      delegate_to: localhost
      run_once: true
      when: status_results.stdout is search('Changes')

    - name: Push the changes
      command: "git push origin master"
      args:
        chdir: "{{ cve_data_dir }}"
      run_once: true
      when: status_results.stdout is search('Changes')
      delegate_to: localhost
  when: cve_data_repository is defined
