- name: Load existing CVE Data
  block:
    - name: Clone the backup repo
      git:
        repo: "{{ cve_data_repository }}"
        dest: "{{ cve_data_dir }}"
        accept_hostkey: yes
        force: yes
        key_file: "~/.ssh/id_rsa"
      register: clone_result

    - name: Check that CVE file exists
      stat:
        path: "{{ cve_data_file }}"
      register: stat_result

    - name: Include existing CVE data as var
      include_vars:
        file: "{{ cve_data_file }}"
        name: existing_cve_data
      when: stat_result.stat.exists

    - name: Map existing IOS CVE IDs to list
      set_fact:
        existing_ios_cves: "{{ existing_cve_data.ios | json_query('*.*[*].cves')|list|flatten|unique }}"
      when: existing_cve_data.ios is defined

    - name: Map existing IOS-XE CVE IDs to list
      set_fact:
        existing_iosxe_cves: "{{ existing_cve_data.iosxe | json_query('*.*[*].cves')|list|flatten|unique }}"
      when: existing_cve_data.iosxe is defined

    - name: Map existing NXOS CVE IDs to list
      set_fact:
        existing_nxos_cves: "{{ existing_cve_data.nxos | json_query('*.*[*].cves')|list|flatten|unique }}"
      when: existing_cve_data.nxos is defined

    - name: Merge Existing IOS CVEs Into Existing CVE Dictionary
      set_fact:
        existing_cves: "{{ existing_cves | default({}) | combine({ 'ios': existing_ios_cves }) }}"
      when: existing_ios_cves is defined

    - name: Merge Existing IOSXE CVEs Into Existing CVE Dictionary
      set_fact:
        existing_cves: "{{ existing_cves | default({}) | combine ({ 'iosxe': existing_iosxe_cves }) }}"
      when: existing_iosxe_cves is defined

    - name: Merge Existing NXOS CVEs Into Existing CVE Dictionary
      set_fact:
        existing_cves: "{{ existing_cves | default({}) | combine ({ 'nxos': existing_nxos_cves }) }}"
      when: existing_nxos_cves is defined

  when:
    - cve_data_repository is defined
    - cve_data_dir is defined
  delegate_to: localhost
  run_once: true
