---
- name: Load Existing CVE Data
  include_tasks: data_load.yml
  when:
    - cve_data_repository is defined
    - cve_data_dir is defined

- name: Include OS Specific Tasks
  include_tasks: "{{ ansible_network_os }}.yml"
  when: ansible_network_os == 'nxos' or ansible_network_os == 'ios'

- name: Get Device Data Set
  set_fact:
    device_data: "{{ hostvars | net_version_mapping }}" #net_version_mapping is found in filter_plugins
  delegate_to: localhost
  run_once: true

- name: Get Cisco Psirt API Data
  include_tasks: cisco_psirt.yml
  when: ansible_network_os == 'nxos' or ansible_network_os == 'ios'

- name: Compile CVE Data
  include_tasks: cve_data.yml

- name: Include Confluence Tasks
  include_tasks: confluence.yml
  when: enable_confluence

- name: Include GIT Backup Tasks
  include_tasks: data_backup.yml
  when: enable_git_backup
