---
- name: Include OS Specific Tasks
  include_tasks: "{{ ansible_network_os }}.yml"

- name: Get Device Data Set
  set_fact:
    device_data: "{{ hostvars | net_version_mapping }}" #net_version_mapping is found in filter_plugins
  delegate_to: localhost
  run_once: true

- name: Get Cisco Psirt API Data
  include_tasks: cisco_psirt.yml
  when: ansible_network_os == 'nxos' or ansible_network_os == 'ios'

- name: Include Confluence Tasks
  include_tasks: confluence.yml
  when: enable_confluence
