- name: Send notification message via Mattermost
  mattermost:
    url: "{{ mattermost_url }}"
    api_key: "{{ mattermost_token }}"
    channel: "{{ mattermost_channel }}"
    text: "{{ lookup('template','templates/mattermost.j2') }}"
    validate_certs: no
  when: device_groups is not defined
  run_once: true
